/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: talenx.theme.ts
 * Command: astryx theme build talenx.theme.ts --out ..\elizax_talenx\css\astryx-talenx.css
 * Generated: 2026-07-26T06:05:35.551Z
 */

/**
 * talenx theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { talenxTheme } from './talenx';
 *   import './talenx.css';
 */
export const talenxTheme = {
  name: 'talenx',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#1F7AF0, #B5C4FF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #002F79)",
    "--color-neutral": "light-dark(#1A1B221A, #E1E2EC33)",
    "--color-background-surface": "light-dark(#FBFCFF, #1A1B22)",
    "--color-background-body": "light-dark(#EFF0FA, #0F1018)",
    "--color-overlay": "light-dark(#1A1B2266, #1A1B2299)",
    "--color-overlay-hover": "light-dark(#1A1B220D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1A1B221A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#1A1B220D, #1A1B2280)",
    "--color-text-primary": "light-dark(#1A1B22, #E1E2EC)",
    "--color-text-secondary": "light-dark(#444653, #A8AAB9)",
    "--color-text-disabled": "light-dark(#8E909E, #5B5E6B)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#1A1B22, #E1E2EC)",
    "--color-icon-secondary": "light-dark(#444653, #A8AAB9)",
    "--color-icon-disabled": "light-dark(#8E909E, #5B5E6B)",
    "--color-background-card": "light-dark(#FBFCFF, #1A1B22)",
    "--color-background-popover": "light-dark(#FBFCFF, #2F3037)",
    "--color-background-inverted": "light-dark(#1A1B22, #FBFCFF)",
    "--color-border": "light-dark(#1A1B221A, #EFF0FA1A)",
    "--color-border-emphasized": "light-dark(#A8AAB9, #444653)",
    "--color-skeleton": "light-dark(#A8AAB9, #444653)",
    "--color-track": "light-dark(#A8AAB9, #444653)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--radius-none": "0px",
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--radius-page": "28px",
    "--radius-chat": "28px",
    "--radius-full": "9999px",
    "--duration-fast-min": "130ms",
    "--duration-fast": "175ms",
    "--duration-fast-max": "235ms",
    "--duration-medium-min": "310ms",
    "--duration-medium": "410ms",
    "--duration-medium-max": "545ms",
    "--duration-slow-min": "730ms",
    "--duration-slow": "975ms",
    "--duration-slow-max": "1300ms",
    "--font-family-body": "Pretendard, -apple-system,Malgun Gothic,sans-serif",
    "--font-family-heading": "Pretendard",
    "--font-family-code": "\"JetBrains Mono\", ui-monospace,Consolas",
    "--color-trust": "light-dark(#23408E, #8fa8e8)",
    "--color-trust-warm": "light-dark(#C2410C, #f0906a)"
  },

};
