/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: talenx.theme.ts
 * Command: astryx theme build talenx.theme.ts --out ..\elizax_talenx\css\astryx-talenx.css
 * Generated: 2026-07-26T06:05:35.551Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const talenxTheme: DefinedTheme;
